#!/bin/bash

# Script to copy to clipboard password from 1password account

# Check if dependencies exist
xclip -version >/dev/null || exit
stvars >/dev/null || exit
op -v >/dev/null || exit
jq --version >/dev/null || exit

token=$(stvars get onetoken)

gettoken() {
  key=$(dmenuwrap -P -p "Enter master key")
  
  [[ -z "$key" ]] && exit
  
  token=$(op signin my -r <<< "$key")
  stvars set onetoken "$token"
}

if [[ -z "$token" ]]; then
  gettoken
fi

items=$(op list items --session "$token" 2>&1)
status=$(echo "$items" | grep "Invalid session token\|session expired")

if [[ ! -z "$status" ]]; then
  gettoken
  items=$(op list items --session "$token" 2>&1)
fi

chosen=$(echo "$items" | jq '.[].overview.title' -r | dmenuwrap -i -p "Get password for")
[[ -z "$chosen" ]] && exit

password=$(op get item $chosen --session "$token" --fields password)

echo "$password" | xclip -selection clipboard
echo "$password" | xclip -selection primary

notify-send "📋 Password for $chosen copied to clipboard"
