#!/bin/bash

# Script to connect/disconnect to Samba Folder in your network

# Check if dependancies exist
dmenu -v >/dev/null || exit # dmenu with password patch installed

admin_pass=$(dmenu -P -p "Enter admin password" <&-)

if [[ ! -z "$(ls -A /mnt/smb/)" ]]; then
  disconnect=$(echo -e "No\\nYes" | dmenu -p "Disconnect Samba Folder?")

  [[ "$disconnect" = "Yes" ]] && echo "$admin_pass" | sudo -S umount /mnt/smb && notify-send " Folder Disconnected"

  exit
fi

addresses=$(nmblookup -S WORKGROUP | grep "Looking" | cut -d ' ' -f 5)
options=""

[[ -z "$admin_pass" ]] && exit

[[ -d /mnt/smb ]] || echo "$admin_pass" | sudo -S mkdir /mnt/smb

while read line; do
  name=$(nmblookup -A "$line" | head -2 | tail -1 | cut -d ' ' -f 1 | tr -d '\040\011\012\015')
  options="$options\n$line - $name"
done <<< "$addresses"

address=$(echo -e "$options" | dmenu -i -p "Select address" | cut -d ' ' -f 1)

[[ -z "$address" ]] && exit

password=$(dmenu -P -p "Enter password" <&-)
folders=$(smbclient -L "$address" -U "user%$password" | grep -P '\t' | sed 's/^.//' | cut -d ' ' -f 1 | sed '1,2d' | head -n -1)
folder=$(echo -e "$folders" | dmenu -i -p "Select address" | cut -d ' ' -f 1)

[[ -z "$folder" ]] && exit

echo "$admin_pass" | sudo -S mount -t cifs -o username=user //"$address"/"$folder" /mnt/smb/ && notify-send " Folder connected at /mnt/smb"
